### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by dlsrbgg33** [uark-cviu/DyGLIP#1]
Hi,

Thank you for your great contribution to the MTMC community.

Do you have a plan to release the code?

Thank you.

**Comment by fengxiuyaun** [comment]
Thank you

**Comment by antenna-fast** [comment]
Nice work, looking for your open source code, specially compere methods on CAMPUS/EPFL dataset

**Comment by cassiaaaaaa** [comment]
thank you

**Comment by qkgia** [comment]
The initial version is released. Thanks for your interest.
