### ISSUE TITLE
Where is train.py ?

### ISSUE THREAD

**Issue by FlowlionAI** [uark-cviu/DyGLIP#8]
Good morning/afternoon.
I discovered your research paper and the associated program, I find it very interesting and I thank you.
However, in part 2 of your code: "GraphFeature", your file "run_script.py" calls the file "train.py". The problem is that the file is missing.
Where can I find it? Or did you drop it if it is already present?
Thanks

**Comment by qkgia** [comment]
@langv26 Thank you for your interest in our paper. We only released the inference code for now.
